import { useState } from 'react';
import Modal from '../components/Modal';
import Button from '../components/Button';


function ModalPage() {
    const [showModal, setShowModal] = useState(false);

    const handleClick = () => {
        setShowModal(true);
    };

   const handleClose = () => {
       setShowModal(false);
    }
    const actionBar = (
        <div>
            <Button primary onClick={handleClose}>I Accept</Button>
        </div>
    );
    const modal = <Modal onClick={handleClose} actionBar={actionBar}>
        <p>
        Here is an important agreement for you to accept. 
        </p>
    </Modal>

    return (
        <div>
            
            <Button
                onClick={handleClick} primary>
                Open Modal
            </Button>
            {showModal && modal}
            <p>facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.</p>

            <p>facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.</p>

            <p>facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.</p>

            <p>facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.facilisis at bibendum id, auctor sit amet quam. Integer elit lectus, ultricies vitae mattis vel, vestibulum vel dui. Nullam venenatis ipsum tortor, at rhoncus urna posuere in. Sed dictum neque mi, vitae semper erat lobortis ut. Vivamus mollis rhoncus magna non dignissim. In condimentum nisl et tortor commodo, in elementum odio aliquam. Suspendisse eget dictum velit, ac rhoncus dui. Aenean ullamcorper sit amet ligula in elementum. Etiam quis leo odio. Curabitur ut turpis placerat, rhoncus dolor in, aliquet augue. Suspendisse ac efficitur ex.</p>
            
        </div>
    );
}

export default ModalPage;